### ISSUE TITLE
Template handling in mkstemp is inconsistent with the system command

### ISSUE THREAD

**Issue by jaseemabid** [haskell/unix#112]
The template string `XXXXXX` is unconditionally appended to template all the time, which prevents users from generating temp files with specific extensions. 

https://github.com/haskell/unix/blob/63a560bf26a052d381cc0662baf2a25e0f3ddc5d/System/Posix/Temp.hsc#L49

This differs from the behavior of the system command as well, see the example

```
$ mktemp /tmp/testXXX.ll
/tmp/testJ0N.ll

λ mkstemp "/tmp/testXXX.ll"
("/tmp/testXXX.llGFEbol",{handle: <file descriptor: 15>})
```

Does it make sense to just delete this line and stick with the behaviour of the system command? Happy to write a patch and test this out. As of now, the system command can generate something of the form `helloXXX.hs` while the Haskell wrapper cannot do that.

**Comment by glguy** [comment]
You can use [`mkstemps`](http://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Temp.html#v:mkstemps) instead.
