### ISSUE TITLE
`getProcessStatus` return extra status when `Stopped`

### ISSUE THREAD

**Issue by wangbj** [haskell/unix#114]
When the process is being ptraced, `WIFSTOPPED` could extract extra information from `status`, see `man 2 ptrace` (excerpt):

```
             PTRACE_O_TRACECLONE (since Linux 2.5.46)
                     Stop  the  tracee at the next clone(2) and automatically start tracing the newly cloned process, which will start with a SIGSTOP, or PTRACE_EVENT_STOP if PTRACE_SEIZE was used.  A waitpid(2) by the tracer will
                     return a status value such that

                       status>>8 == (SIGTRAP | (PTRACE_EVENT_CLONE<<8))

```

Right now `getProcessStatus` returns only `Stopped sigTRAP` in this case, the extra status (bit 16-23) is lost. Is it possible to return `Stopped Signal CInt` instead? I'm not sure if this only applies to Linux, since I have no Unix machine.

**Comment by hvr** [comment]
Well, `ptrace(2)` isn't standardised by POSIX and therefore not in scope for the `unix` package

**Comment by hs-viktor** [comment]
Can we close this?
