### ISSUE TITLE
Change return type of `exitImmediately`

### ISSUE THREAD

**Issue by erikd** [haskell/unix#126]
Currently `exitImmediately` has a type:
```
exitImmediately :: ExitCode -> IO ()
```
and the documentation explicitly states that it never returns.

*Since* it never returns, it makes more sense for the type to be:
```
exitImmediately :: ExitCode -> IO a
```
to match the type of `System.Exit.exit` and related functions.

In addition, it would be good to extend the docs to state that unlike the `System.Exit.exit` family of functions, `exitImmediately` does not work via the Haskell exception system and hence, `exitImmediately` cannot be caught with an exception handler.

**Comment by hvr** [comment]
Makes sense; however generalizing the type-signature this way does represent a breaking change in the presence of class constraints on the return type; so this would be unix-2.8 material
