### ISSUE TITLE
add byte order conversion functions htonl ntohl etc

### ISSUE THREAD

**Issue by joeyh** [haskell/unix#127]
These were exported from network before 3.0.0.0 but it stopped exporting them since it's moving toward being a higher-level portable API. But htonl ntohl etc are still part of POSIX and ought to be exposed somewhere in the Haskell ecosystem for those cases where one does need to convert between host and network byte order. So I suggest adding them to this package.

**Comment by clkamp** [comment]
I tried to solve it the other way around, because https://github.com/haskell/unix/blob/master/System/Posix.hs#L108 states, that these functions should be in network (see haskell/network#436)

**Comment by hs-viktor** [comment]
These are of course rather cheap to just FFI as needed, and generate very compact code, so it is at this point perhaps easier to just roll your own, than jump through hoops ensuring that you have some future version of `unix` that picks up the slack from `network`.
```
0000000000409980 <ghczuwrapperZC0ZCmainZCMainZChtons>:
  409980:       89 f8                   mov    %edi,%eax
  409982:       66 c1 c0 08             rol    $0x8,%ax
  409986:       c3                      retq

0000000000409990 <ghczuwrapperZC1ZCmainZCMainZChtons>:
  409990:       89 f8                   mov    %edi,%eax
  409992:       66 c1 c0 08             rol    $0x8,%ax
  409996:       c3                      retq

00000000004099a0 <ghczuwrapperZC2ZCmainZCMainZChtonl>:
  4099a0:       89 f8                   mov    %edi,%eax
  4099a2:       0f c8                   bswap  %eax
  4099a4:       c3                      retq

00000000004099b0 <ghczuwrapperZC3ZCmainZCMainZChtonl>:
  4099b0:       89 f8                   mov    %edi,%eax
  4099b2:       0f c8                   bswap  %eax
  4099b4:       c3                      retq   
```

The demo code is:
```haskell
{-# LANGUAGE CApiFFI, MagicHash, UnboxedTuples #-}
module Main (main) where

import Data.Int
import GHC.IO (IO(..))
import GHC.Exts (realWorld#)
import Numeric (showHex)

foreign import capi unsafe "arpa/inet.h htonl" c_htonl :: Int32 -> IO Int32
foreign import capi unsafe "arpa/inet.h htonl" c_ntohl :: Int32 -> IO Int32
foreign import capi unsafe "arpa/inet.h htons" c_htons :: Int16 -> IO Int16
foreign import capi unsafe "arpa/inet.h htons" c_ntohs :: Int16 -> IO Int16

htonl, ntohl :: Int32 -> Int32
htonl i = case c_htonl i of
    IO a -> case a realWorld# of { (# _, j #) -> j }
ntohl i = case c_ntohl i of
    IO a -> case a realWorld# of { (# _, j #) -> j }

htons, ntohs :: Int16 -> Int16
htons i = case c_htons i of
    IO a -> case a realWorld# of { (# _, j #) -> j }
ntohs i = case c_ntohs i of
    IO a -> case a realWorld# of { (# _, j #) -> j }

main :: IO ()
main = do
    putStrLn $ showHex (htonl 0x12345678) ""
    putStrLn $ showHex (ntohl 0x12345678) ""
    putStrLn $ showHex (htons 0x1234) ""
    putStrLn $ showHex (ntohs 0x1234) ""
```
Which on a little-endian (Intel) machine outputs:
```
$ ./foo
78563412
78563412
3412
3412
```
But it is rather unclear what purpose such conversions serve outside of data serialisation.  Is getting back an integral value actually useful, or is the goal to store native numbers in network order into binary buffers and load data from binary buffers into native numbers.  And if that's the case why not use `Data.Binary` to perform the serialisation as part of encoding some larger structure?  See [putWord32be](https://hackage.haskell.org/package/binary-0.10.0.0/docs/Data-Binary-Put.html#v:putWord32be) et. al.

So the demo code above is probably not what you want. Instead the natural API would look more like peek/poke taking an address to write serialised data to, or read serialised data from, which is no longer exactly `ntohl` as such.  A robust interface might also need to deal with unaligned buffers, which is again something that `Data.Binary` takes care of.

Also, which module in `unix` would be a good home for these? None of the current modules look like an ideal fit to me.

**Comment by Bodigrim** [comment]
Aren't these functions already present in `GHC.Exts`? https://hackage.haskell.org/package/base-4.16.1.0/docs/GHC-Exts.html#v:byteSwap16-35- and other `byteSwap*#` functions.

**Comment by Bodigrim** [comment]
See also https://hackage.haskell.org/package/network-byte-order-0.1.6

**Comment by hs-viktor** [comment]
Probably not the right package for this.  Can we close?
