### ISSUE TITLE
A Unix 2.7 that depends on time 1.9?

### ISSUE THREAD

**Issue by erikd** [haskell/unix#131]
Version 1.9 of time has [nominalDiffTimeToSeconds](https://hackage.haskell.org/package/time-1.9.2/docs/Data-Time-Clock.html#v:nominalDiffTimeToSeconds) which is rather useful.

Is it possible to release a Unix 2.7 depending on this version of the time package?

**Comment by chessai** [comment]
I don't see why not. I'm not aware of any compatibility issues.

**Comment by erikd** [comment]
On the `2.7` branch, the cabal file already has:
```
        time        >= 1.2     && < 1.10
```
I think we just need an actual release.

**Comment by fgaz** [comment]
+1 for a release. time 1.9 has _a lot_ of nice additions!

**Comment by hvr** [comment]
I'm waiting for whether GHC 8.8.1 requires a patch release of `unix` or not; if it doesn't I'll do a revision; if it needs a patch-release I'll do that; but I don't intend to do both.

**Comment by hvr** [comment]
resolved via http://hackage.haskell.org/package/unix-2.7.2.2/revision/3.cabal
