### ISSUE TITLE
Cut a release for GHC 8.8.1

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#132]

**Comment by bgamari** [comment]
Ping.

**Comment by hvr** [comment]
@bgamari as far as I can see, we can get away with a metadata revision as there's no code changes necessary; i.e. we don't need an actual new release for GHC 8.8.1

Consequently I've made a revision to sync up the metadata to Hackage, and tagged https://github.com/haskell/unix/releases/tag/v2.7.2.2-r3 accordingly

**Comment by bgamari** [comment]
Thanks!
