### ISSUE TITLE
way to prevent openDirStream from following symlinks

### ISSUE THREAD

**Issue by joeyh** [haskell/unix#134]
https://github.com/haskell/directory/issues/97 needs a way to list the content of a directory that avoids following a symlink. The unix way to do that is `open` with `O_NOFOLLOW` and then passing the fd to `fdopendir`. This library does not provide a way to do that; could it?

-----

One way would be to add 

    openDirStreamFromFd :: Fd -> IO DirStream

But that is fairly low-level. The user needs to take care to avoid reusing the Fd after calling it. Also, while some of the OpenFileFlags may make sense for opening a directory, most of them probably don't. And the user would need to take care to set `O_CLOEXEC` to avoid a possible fd leak.

This interface would avoid those problems (pass `O_CLOEXEC` always):

    data OpenDirFlags = OpenDirFlags { dir_nofollow :: Bool, ... }

    openDirStream' :: OpenDirFlags -> IO DirStream

Assuming this is exported from the same module as OpenFileFlags, the fields in OpenDirFlags need to be qualified to avoid name conflicts. Or OpenFileFlags could be used for openDirStream', but a number of those flags don't make sense for opening a directory.

Also openDirStream could be changed to take such an OpenDirFlags, if an API bump appeals.

I'd be happy to implement whichever of these you prefer.

**Comment by hasufell** [comment]
Check https://hackage.haskell.org/package/hpath-io-0.10.0/docs/System-Posix-Directory-Traversals.html for inspiration, which has fdopendir.

https://github.com/hasufell/hpath/blob/3b6eb46dc9a95395afe06b8cf5ec507e264628fc/hpath-io/src/System/Posix/Directory/Traversals.hs#L226-L245

**Comment by hasufell** [comment]
Seems there already is a PR: https://github.com/haskell/unix/pull/110

**Comment by Rufflewind** [comment]
Any such implementation would need to support Windows.  I think it is possible, given that Cygwin implements it, but it involves touching some rather exotic APIs like [`NtQueryDirectoryFile`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfile): https://github.com/Alexpux/Cygwin/blob/b39cd00f07e8df11c5446fb35da490ef85f12821/winsup/cygwin/fhandler_disk_file.cc#L2186

It's also important to define the behavior of `dir_nofollow` on POSIXes that don't support `O_NOFOLLOW`.  I think the safest and simplest fallback would be to just raise an exception and let the user decide what non-atomic alternative they want to use.

**Comment by hs-viktor** [comment]
With #110 merged, can we close this?

**Comment by Rufflewind** [comment]
Are there plans to release #110 any time soon? `directory` is unable to use the new functionality to resolve https://github.com/haskell/directory/issues/97 if the changes aren't released.

**Comment by Bodigrim** [comment]
Yes, we are likely to make a release soon (but not immediately).
