### ISSUE TITLE
Cut release for GHC 8.10.1

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#143]
GHC 8.10.1 will ship with `unix` based upon 2fe6d8b7ab1e4137876705eb58b7909bb1107a05. It would be great to cut a release based based upon this commit sometime in the next week.

**Comment by bgamari** [comment]
@hvr, ping.

**Comment by hvr** [comment]
@bgamari I see no need/justification for a new release; the only relevant change as far as Hackage is concenred I see unless I'm missing something, is a version constraint tweak which can be accomplished by a hackage metadata revision

**Comment by bgamari** [comment]
Well, there are testsuite changes but perhaps these are not considered Hackage-relevant.
