### ISSUE TITLE
Support time 1.10

### ISSUE THREAD

**Issue by sjakobi** [haskell/unix#150]
[Changelog for time-1.10](http://hackage.haskell.org/package/time-1.10/changelog).

**Comment by hvr** [comment]
This needs a strategy for CI which is the main reason I'm reluctant to blindly relax bounds for `time` in any of the packages I maintain until there's a GHC release that includes `time-1.10.`

**Comment by bgamari** [comment]
@hvr, why not simply add a new configuration with `--constraints=time>=1.10` to the CI matrix? `unix` currently doesn't depend transitively upon `ghc` so building against `time-1.10` shouldn't be a problem.

**Comment by devwout** [comment]
This is a fundamental library, which only seems to depend on the `POSIXTime` type of the `time` library. By not relaxing the bounds, people are being prevented from upgrading the time library, which has some useful fixes in 1.10 . Why can't we be practical and relax the bounds?

**Comment by sjakobi** [comment]
> @hvr, could we not add a new configuration with `--constraints=time>=1.10` to the CI matrix?

Apparently this can be nicely configured with `haskell-ci` too:

https://github.com/haskell-CI/haskell-ci/blob/1d023c415d4f320787f4851d38ee7da01a7756e5/cabal.haskell-ci#L86-L99
