### ISSUE TITLE
fileAllocate handles errors incorrectly on some systems

### ISSUE THREAD

**Issue by matil019** [haskell/unix#156]
Nice to meet you.

`System.Posix.Fcntl.fileAllocate` appears to handle errors incorrectly. On Linux, `posix_fallocate(3)` states:

> RETURN VALUE
>        posix_fallocate() returns zero on success, or an error number on failure.  Note that errno is not set.

On NetBSD, [`posix_fallocate(2)` has the same behavior](https://netbsd.gw.com/cgi-bin/man-cgi?posix_fallocate+2+NetBSD-7.0).

However, on FreeBSD [`posix_fallocate(2)` returns -1 and sets `errno`](https://www.freebsd.org/cgi/man.cgi?query=posix_fallocate&sektion=2&manpath=FreeBSD+8.3-RELEASE).

`fileAllocate` is [implemented with `throwErrnoIfMinus1_`](https://github.com/haskell/unix/blob/master/System/Posix/Fcntl.hsc#L95) assuming `errno` is set. So it would work on FreeBSD but not on the other OSes.

The correct implementation would be like:

```hs
fileAllocate fd off len = do
  ret <- c_posix_fallocate (fromIntegral fd) (fromIntegral off) (fromIntegral len)
  case () of
    _ | ret == 0 -> pure ()
      -- FreeBSD-style error
      | ret == -1 -> throwErrno "fileAllocate"
      | otherwise -> ioError (errnoToIOError "fileAllocate" (Errno ret) Nothing Nothing)
```

or some `#if/#else` guards rather than this hack?

**Comment by hs-viktor** [comment]
Would you care to open a PR?

**Comment by Bodigrim** [comment]
@matil019 yes, please go ahead.

**Comment by matil019** [comment]
@hs-viktor @Bodigrim Done!

**Comment by vdukhovni** [comment]
My own server is running `FreeBSD 12.2-RELEASE-p14`.  The manpage for `pofix_fallocate` states:
```
RETURN VALUES
     If successful, posix_fallocate() returns zero.  It returns an error on
     failure, without setting errno.
```
The same is true with [FreeBSD 12.0](https://www.freebsd.org/cgi/man.cgi?query=posix_fallocate&apropos=0&sektion=2&manpath=FreeBSD+12.0-RELEASE&arch=default&format=html)
and [FreeBSD 11.0](https://www.freebsd.org/cgi/man.cgi?query=posix_fallocate&apropos=0&sektion=2&manpath=FreeBSD+11.0-RELEASE&arch=default&format=html)

I have to go back to [FreeBSD 10.0](https://www.freebsd.org/cgi/man.cgi?query=posix_fallocate&apropos=0&sektion=2&manpath=FreeBSD+10.0-RELEASE&arch=default&format=html) to find the reported behaviour documented.

So the correct behaviour is now the same for FreeBSD as for Linux and NetBSD.  There does not appear to be a posix_fallocate for MacOS...
