### ISSUE TITLE
Release for GHC 9.0.1

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#173]
GHC could use a release of ea13d990580273a883368793dfbb826cab5a22d4 for 9.0.1

**Comment by Bodigrim** [comment]
I've revised `unix-2.7.2.2` to allow `base-4.15`. Would it be enough? There are both a Hackage release and a git commit (I suggest you bump `unix` submodule to 21437f20a41eb1a4c7d42fc402fe91350eb8b03d, which is the head of 2.7 branch).

**Comment by bgamari** [comment]
Indeed, that is perfect. Thank you, @Bodigrim!
