### ISSUE TITLE
System.Posix.Semaphore.semWait is marked "safe"

### ISSUE THREAD

**Issue by duog** [haskell/unix#179]
This means it blocks the haskell capability. If seems it would be much more useful if it were marked "unsafe" so that other threads could proceed on the running capability. Perhaps we need a new function instead?

**Comment by adamse** [comment]
IIUC what you want is what "safe" does. It returns the capability to the scheduler so it can run other haskell code (the rts will spawn a new os thread to run the capability).

**Comment by duog** [comment]
How embarrassing!  So then I suppose the documentation for `semWait` is wrong, or perhaps it only to the non-threaded runtime.

**Comment by adamse** [comment]
The docs are weird.
