### ISSUE TITLE
Make current maintainers explicit

### ISSUE THREAD

**Issue by andreasabel** [haskell/unix#215]
Prompted by the maintainer application of @hasufell on libraries@haskell.org.

The cabal file claims `maintainer: libraries@haskell.org` which is rather silly, can we fix this?
https://github.com/haskell/unix/blob/4c67c356e9b742c040ec59897864ea542f1cfd79/unix.cabal#L8

**Comment by hasufell** [comment]
Just to link the actual thread for others: https://mail.haskell.org/pipermail/libraries/2022-May/031611.html

**Comment by hasufell** [comment]
@Bodigrim who are the current maintainers?

**Comment by Bodigrim** [comment]
@hs-viktor aka @vdukhovni, you and me.
