### ISSUE TITLE
Release Planning: unix-2.7.3 (GHC 9.4.1)

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#234]
We are quickly approaching the final GHC 9.4.1 release. We are currently using f018fe126c5f1dbbd3431c7214337ccbb38230ce although are open to advancing to a later commit assuming it constitutes only a minor bump.

**Comment by hasufell** [comment]
There sre a couple of bugfixes we should backport:

* https://github.com/haskell/unix/pull/229
* https://github.com/haskell/unix/pull/228
* https://github.com/haskell/unix/pull/207
* https://github.com/haskell/unix/pull/144
* https://github.com/haskell/unix/pull/122
* https://github.com/haskell/unix/pull/119

**Comment by hasufell** [comment]
Backports here: https://github.com/haskell/unix/pull/235

**Comment by hasufell** [comment]
703690614518f38306a81985fb587ee77cf40c48 should work for 9.4. It's unix 2.7.3

**Comment by bgamari** [comment]
Thanks @Julian!
