### ISSUE TITLE
RELEASE 2.7.3

### ISSUE THREAD

**Issue by hasufell** [haskell/unix#244]
@bgamari what is the schedule for this?

**Comment by Bodigrim** [comment]
GHC 9.4.1 was released with 70369061, so we should upload it onto Hackage as `unix-2.7.3`.

**Comment by hasufell** [comment]
I'm a bit confused. There seems to be very little communication with core library maintainers during GHC release management. I was not notified that GHC will ship with this. The release was not finalized by unix maintainers, yet it was bundled in GHC.

**Comment by bgamari** [comment]
I am also confused; nearly a month ago I was told (https://github.com/haskell/unix/issues/234#issuecomment-1189829294) that 7036906 should work and "was 2.7.3".

**Comment by hasufell** [comment]
@bgamari apologies, then that was miscommunication from my side. I'd suggest for the future that a hackage release should precede the GHC release.

Does that sound reasonable?

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/unix-2.7.3

**Comment by bgamari** [comment]
> Does that sound reasonable?

Absolutely and I completely agree. I'll try to be more clear in the future in the tickets asking for a releases for GHC that we want not just a commit but a Hackage release.
