### ISSUE TITLE
Consider using CirrusCI for AArch64 CI?

### ISSUE THREAD

**Issue by NicolasT** [haskell/unix#250]
CI for AArch64 currently uses (I presume) Qemu-based emulation on a GitHub Actions worker. This is... very slow. Since CirrusCI is already used for FreeBSD testing, and CirrusCI seems to provide AArch64 (Linux) container environments, would it make sense to use this instead?

This doesn't provide a solution for ARM7, though.

**Comment by Bodigrim** [comment]
I'm not sure, in general I'd prefer to stick to GHA as much as possible. Let's deal with the deluge of your existing PRs first :)

**Comment by hasufell** [comment]
I'd actually much rather migrate this repo to GHC gitlab and have easy access to all GHC architecture is.

**Comment by NicolasT** [comment]
Clear :)
