### ISSUE TITLE
Include GHC 9.4 in CI ?

### ISSUE THREAD

**Issue by andreasabel** [haskell/unix#264]
I have come here because I get a library problem with `unix` under the `ubuntu-22.04` virtual environment when used with GHC 9.4.2 and static linking:
```
/home/runner/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/lib/../lib/x86_64-linux-ghc-9.4.2/unix-2.7.3/libHSunix-2.7.3.a(Files.o):
function ghczuwrapperZC1ZCunixzm2zi7zi3ZCSystemziPosixziFilesZCmknod: 
error: undefined reference to '__xmknod'
```
(See https://github.com/agda/agda/actions/runs/3603326548/jobs/6071389168#step:11:38.)

Maybe such problems could be caught if the CI here included GHC 9.4 and also something that tests static linking (`--enable-executable-static`).

Is there a reason that GHC 9.4 isn't included in the CI?  After all, it ships with `unix`.

**Comment by hasufell** [comment]
> Is there a reason that GHC 9.4 isn't included in the CI? 

Mostly that we don't get paid.

**Comment by Bodigrim** [comment]
A PR adding GHC 9.4 to the build matrix would be welcome.

**Comment by andreasabel** [comment]
> A PR adding GHC 9.4 to the build matrix would be welcome.

See:
- #266
