### ISSUE TITLE
`unix-2.8` release for GHC 9.6

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#272]
It be great to have a release on the 2.8 branch in the next few weeks to ship with GHC 9.6.1. We are currently using 98adc732bfbfca4fef945d546ecbaae13952a950 which is an 17 commits ahead of `v2.8.0.0`. If necessary we can revert to a revision of `v2.8.0.0` but we would prefer not to due to the many WASI fixes in `master.`

**Comment by Bodigrim** [comment]
I think `master` branch is good to go, unless there is an appetite to squeeze #251 into.

@hasufell could you please take care of this release?

**Comment by hasufell** [comment]
@bgamari is 978e4e781b3a26a3d6b2f17efba7dbc176eca798 ok? There are two more interesting commits:

* a170937c783df07ad4da653566a2cf6eafbe3566
* 3fe57f354385da3f0b7543c93eab14e8b8c28137

**Comment by Bodigrim** [comment]
@hasufell if you want to double-check, you can bump GHC submodule and see how it goes before cutting a release. But I believe we want to include both of the commits in the release.

**Comment by hasufell** [comment]
* https://hackage.haskell.org/package/unix-2.8.1.0
* https://github.com/haskell/unix/releases/tag/v2.8.1.0
* commit is: 720debbf5b89366007bac473e8d7fd18e4114f1a
