### ISSUE TITLE
`System.Posix.Env.ByteString.getEnvironment` segfaults on empty environment

### ISSUE THREAD

**Issue by sol** [haskell/unix#274]
Repro:
```haskell
import System.Posix.Env.ByteString

main :: IO ()
main = do
  clearEnv
  getEnvironment >>= print
```
The the technical issue is a missing null pointer check, but the real reason is that we have a lot of copy & paste code that has diverged.

**Comment by sol** [comment]
> Can you say which version you used?

From what `git blame` tells me, all versions since that module was added should be affected (same for [`System.Posix.Env.PosixString`](https://hackage.haskell.org/package/unix-2.8.1.0/docs/System-Posix-Env-PosixString.html) BTW).  If you can't reproduce it make sure you are on Linux.

**Comment by sol** [comment]
Specifically 34c7bf896f19b182cf6fa104e057f1df9df1254a added that code (copied from `System.Posix.Env` I assume) and 335fd69c61076db160fe7011814e26a577958147 fixes the bug for `System.Posix.Env` but leaves  `System.Posix.Env.ByteString` unchanged.

**Comment by hasufell** [comment]
Released: https://hackage.haskell.org/package/unix-2.8.1.1

I also informed @bgamari to bump this in GHC.

**Comment by sol** [comment]
Thanks @hasufell.
