### ISSUE TITLE
System.Posix.User stopped exporting UserEntry

### ISSUE THREAD

**Issue by joeyh** [haskell/unix#281]
Prior to unix-2.8.0.0, System.Posix.User exported UserEntry. It no longer does, and it's only available from System.Poxis.User.ByteString. Necessitating some ugly cpp to handle both versions in code that uses the type. I suspect this was an accident, and System.Posix.User should re-export UserEntry.

**Comment by hasufell** [comment]
You probably want https://hackage.haskell.org/package/unix-2.8.1.1/docs/System-Posix-User.html#v:homeDirectory
