### ISSUE TITLE
Memory unsafety in `withFilePath` in 2.8.2.0

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#295]
### Your environment

All.

### Steps to reproduce
```
ghci> :set -XOverloadedStrings
ghci> import qualified Data.ByteString.Short as BSS
ghci> import Data.ByteString.Internal (c_strlen)
ghci> BSS.useAsCStringLen "ScriptEnv0.hs" $ \(ptr, len) -> c_strlen ptr >>= \clen -> print (clen, len)
```

### Expected behaviour
```
(13,13)
```

### Actual behaviour
```
ghci> :set -XOverloadedStrings
ghci> import qualified Data.ByteString.Short as BSS
ghci> import Data.ByteString.Internal (c_strlen)
ghci> BSS.useAsCStringLen "ScriptEnv0.hs" $ \(ptr, len) -> c_strlen ptr >>= \clen -> print (clen, len)
(13,13)
ghci> BSS.useAsCStringLen "ScriptEnv0.hs" $ \(ptr, len) -> c_strlen ptr >>= \clen -> print (clen, len)
(38,13)
ghci> BSS.useAsCStringLen "ScriptEnv0.hs" $ \(ptr, len) -> c_strlen ptr >>= \clen -> print (clen, len)
(29,13)
ghci> BSS.useAsCStringLen "ScriptEnv0.hs" $ \(ptr, len) -> c_strlen ptr >>= \clen -> print (clen, len)
(38,13)
```

This is due to https://github.com/haskell/unix/pull/279/files#diff-e155a859a7a42c152728c6296887607bcfe0a7b0213d98573053e137ed8ebb32R157, which incorrectly relies on `strlen` on a string produced with `useCString`. This was originally noted in https://github.com/haskell/cabal/pull/9241.

**Comment by bgamari** [comment]
This is fixed in #294.

**Comment by gbaz** [comment]
Should the bytestring documentation be updated to more clearly warn about this footgun with the `useAsCStringLen` function?

**Comment by hasufell** [comment]
Fixed in https://github.com/haskell/unix/pull/294

@Bodigrim are you making the 2.8.2.1 release?

**Comment by Bodigrim** [comment]
If you have a moment, please do, otherwise I'll release in the morning.

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/unix-2.8.2.1

**Comment by hasufell** [comment]
@bgamari pushed tag for your submodules: https://github.com/haskell/unix/releases/tag/v2.8.2.1
