### ISSUE TITLE
Please revise time dependency to < 1.15

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/unix#314]
This works fine, so it seems that `unix` on Hackage could do with a revision to bump `time` to `< 1.15`.

* `cabal repl -z -b 'unix==2.8.5.0' -b 'time>=1.14' --allow-newer=time`

**Comment by hasufell** [comment]
Can you give more context? What's wrong?

**Comment by Bodigrim** [comment]
There is a new release `time-1.14`, so `unix` has to adjust version bounds. Given that we need to release `2.8.5.1` to include bdea7d475e5fb13ea7768a5bbeaaa4600073d829 anyway, we can include relaxation into it as well.

**Comment by Bodigrim** [comment]
@tomjaguarpaw I made a revision to unblock you: https://hackage.haskell.org/package/unix-2.8.5.0/revisions/
