### ISSUE TITLE
Add convenient I/O operations using `ByteString` for payload

### ISSUE THREAD

**Issue by hvr** [haskell/unix#35]
Operations like [`fdRead`](http://hackage.haskell.org/package/unix-2.7.1.0/docs/System-Posix-IO-ByteString.html#v:fdRead) which read the data as `[Char]` are often not what you'd want. Instead you'd want the payload to be a `ByteString`.

Instead of having to roll your own, by using a combination of the `unix-bytestring` and `unix` packages, `unix` ought to directly provide such convenience functions.

See also http://thread.gmane.org/gmane.comp.lang.haskell.libraries/23812/focus=23816

**Comment by hasufell** [comment]
This was really confusing to me. If you are already that low-level that you use the unix package and mess with file descriptors... you are probably very far away from anything String based. You don't really want to write a 10GB file using the String type, do you?

**Comment by centromere** [comment]
I agree with @hvr.

**Comment by onurcanbektas** [comment]
I would like to get start on this issue, but, to be honest, I couldn't understand what is the exact issue ? :)
