### ISSUE TITLE
Is there any way to install the package in Windows?

### ISSUE THREAD

**Issue by etairi** [haskell/unix#45]
Is it possible to install the package under Windows? I tried using MinGW, and I can run `./configure` command. But, what about installation? Clearly, running `cabal install` won't work.

**Comment by hvr** [comment]
I'm afraid it's not supposed to work with GHC/MinGW (it even says so in the package description)...

**Comment by etairi** [comment]
I just gave MinGW as an option. I assume it works with Cygwin, right?

**Comment by Rufflewind** [comment]
> I can't even install it with Cygwin, though it says in the docs it works under Cygwin.

It should work on Cygwin if you use a Cygwin-build of GHC and Cabal.  If it doesn't then it should be considered a bug.

**Comment by rakesh-k** [comment]
I am on Windows and need to install stack-run which depends on this package. And the unix package installation fails with this error:

```
cabal: Error: some packages failed to install:
unix-2.7.2.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by RyanGlScott** [comment]
@rakesh-k, sorry, `unix` simply won't build on Windows.

Long ago, I believe GHC used to have a Cygwin-specific build that would allow you to install POSIX-heavy packages like `unix`, but that is certainly no longer the case. Nowadays, trying to link against the Cygwin runtime using MinGW-w64 libraries will inevitably lead to horrific linker errors, as the two each define their own, incompatible versions of several primitives (e.g., `timer_t`).

The workaround is to find an equivalent way to do things on Windows that doesn't require the `unix` package, I'm afraid. There is a [`unix-compat`](http://hackage.haskell.org/package/unix-compat) package that provides Windows shims for emulating the functionality of much of `unix`, so it's possible that might work for you.

**Comment by RyanGlScott** [comment]
Although now that I look closer, your issue in particular isn't that `stack-run` depends directly on `unix`, but rather that it depends on `vty`, which in turn depends on `unix`. This is [a known issue](https://github.com/jtdaugherty/vty/pull/1), and from what I understand, fixing it is much more complicated than swapping out some `unix` functions for `unix-compat` ones, unfortunately.

**Comment by RyanGlScott** [comment]
@rakesh-k: See also https://github.com/yamadapc/stack-run/issues/6, which tracks the progress to remove `stack-run`'s dependency on `vty` when built with Windows.

**Comment by RyanGlScott** [comment]
Closing since as of e745f0c47a01bad4ed575cfa84bd7c753b2355dd, `unix.cabal` literally prevents you from installing `unix` on Windows due to the aforementioned issues.
