### ISSUE TITLE
Add `System.Posix.MessageQueue`.

### ISSUE THREAD

**Issue by magthe** [haskell/unix#47]
The message queue API is curiously missing from the `unix` package.  Is there a reason for it other than "nobody's cared enough to implement it yet"?

**Comment by argiopetech** [comment]
Both `sys/msg.h` and `mqueue.h` are on the list of "Not Supported" headers in `Posix.hs`. This is in contrast to several headers in the "To be supported" category, so it would appear that message wueurs are blocked for some reason other than lack of volunteers to write an interface. I'm not sure of the rationale for this, but I can look into it.

For the record, can you share a use case that might encourage adoption by the Core Libraries Committee of a patch adding message queues?

**Comment by magthe** [comment]
It's a standard IPC method that differ from (named) pipes:

- They have internal structure (pipes are just about pumping bits)
- They are priority driven and the queue stays ordered so the oldest message with the highest priority is at the front.
- The programmer has control over various aspects of the queue, on creation one can set
    - size of queue (number of messages)
    - max size of message
- It's possible to determine that state of a queue

The use case is of course to allow writing programs in Haskell that communicate via message queues.

**Comment by argiopetech** [comment]
Good enough for me. I'll put some feelers out on the mailing list to see I can determine why (or if) this was slated not to be implemented.

In the event that there is no compelling reason for us not to merge a patch adding this functionality, would you be willing to submit such a patch?

**Comment by magthe** [comment]
Sure, I'd be willing to make an attempt at adding it.

**Comment by argiopetech** [comment]
Thanks! I am, of course, willing to help verify/integrate, but I'm in the middle of a move and remodel at the moment and can't take the lead.

I've thrown a [request for info](https://mail.haskell.org/pipermail/libraries/2015-October/026186.html) on the libraries mailing list. Pending a response there, I see no reason not to integrate anything created. Worst case, it could be spun into a new library.

On that note, `posix-realtme` provides a set of basic wrappers around `mqueue.h` (realtime message queues), which may help with creating a wrapper around `sys/queue.h` or even solve your challenge outright.

**Comment by magthe** [comment]
`mqueue.h` *is* Posix message queues: <http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/mqueue.h.html>

**Comment by argiopetech** [comment]
`mqueue.h` is **REALTIME** (caps and bold per the spec) message queues. One Haskell binding (recently supported, albeit of "provisional" stability) to that header is provided in `posix-realtime`.

What *I* think of as "POSIX Message Queues" is provided by [`sys/msg.h`](http://pubs.opengroup.org/onlinepubs/7908799/xsh/sysmsg.h.html). There is not currently a Haskell binding to those headers of which I am aware.

Which are you looking for? If the former, a solution exists. If the latter, a solution will need to be built. I'll keep this issue open in either case, as I'm legitimately curious why the `unix` library has (potentially) chosen not to support either.

**Comment by magthe** [comment]
`sys/msg.h` is commonly called System V message queues (or XSI message queues).

The message queues I'm interested are the ones specified in `mqueue.h`.

**Comment by argiopetech** [comment]
Fair enough. Good luck with the bindings in posix-realtime.

Pending the mailing list, I may get in touch with Michal Gajda and see if he would like to have posix-realtime integrated into unix.

**Comment by magthe** [comment]
Yes, is there any point in keeping them separate?

**Comment by argiopetech** [comment]
Incompleteness would, of course, be a valid reason not to merge `posix-realtime` into `unix`. Other than that, or an objection by the author of `posix-realtime`, I have no personal knowledge of a reason not to merge them. There may be a historical reason I'm not aware of. The "Unsupported interfaces" list was created in 2002 and hasn't seen much modification, while I've only been maintaining `unix` since earlier this year.

My gut feeling is that the path of least resistance would be to add the missing functionality in `posix-realtime`'s `System.Posix.Realtime.MQueue`, add that file (and any appropriate tests) to `unix`, and submit it as a pull request here on Github to both `unix` and `posix-realtime`. Worst case scenario, you have a usable local copy. Best case scenario it is accepted into `posix-realtime` and into `unix` (again, pending that historical data from the mailing list) and benefits everyone.

**Comment by magthe** [comment]
My need for this has disappeared so I'm closing this.

**Comment by chessai** [comment]
Sorry that it's too late, but https://github.com/andrewthad/posix-api has
great support for posix message queues.
