### ISSUE TITLE
compilation error: sys/mman.h: No such file or directory

### ISSUE THREAD

**Issue by manuel-io** [haskell/unix#49]
Did not found `mman.h` on x86-64 (Ubuntu GNOME) because the sys folder doesn't exist.
I replaced sys with linux and everything is working now:
 
    libc6-dev-i386: /usr/include/sys/mman.h

    linux-libc-dev: /usr/include/linux/mman.h

**Comment by erikd** [comment]
I would consider this an Ubuntu (and possibly even a Debian) bug.

According to the `msync` man page:

```
SYNOPSIS
       #include <sys/mman.h>

       int msync(void *addr, size_t length, int flags);
.....

CONFORMING TO
       POSIX.1-2001.
```

If its conforming to a POSIX spec, it should *not* be under `/usr/include/linux` and it should be in the location specified by the man page.

In your particular instance, I would just install the `libc6-dev-i386` package.

**Comment by erikd** [comment]
Ok, to close this? Installing the `libc6-dev` package should fix it.

**Comment by manuel-io** [comment]
You're right!

    libc6-dev: /usr/include/x86_64-linux-gnu/sys/mman.h

The file was missing on my system. `sudo apt-get install --reinstall libc6-dev` solved!
