### ISSUE TITLE
What's the difference between Catch and CatchOnce?

### ISSUE THREAD

**Issue by chris-martin** [haskell/unix#56]
The `Handler` constructors could use some documentation. In particular, I'm not sure what `CatchOnce` means.

**Comment by edsko** [comment]
+ 1

**Comment by hvr** [comment]
Yes, this should be documented better. The name `CatchOnce` implies that the signal handler is automatically reset (via `SA_RESETHAND`), as opposed to `Catch` which doesn't.

**Comment by edsko** [comment]
It's confusing also because Unix signal handlers typically need to be reinstalled after they are invoked, right? Also, there is a comment in the code someplace that says "it's impossible to get `CatchOnce` right". Would be good to document that too.

**Comment by hvr** [comment]
@edsko there's some history fun fact about that:  SysV and BSD disagree on the semantics of  `signal(2)` regarding whether it's one-shot or not. If you want to cry a little bit, read the gory details in https://linux.die.net/man/2/signal under the "Portability" heading... ;-)
