### ISSUE TITLE
Missing O_NOFOLLOW

### ISSUE THREAD

**Issue by hasufell** [haskell/unix#57]
This is really annoying. I don't even understand why this library attempts to pre-select which flags I can pass in or not. That's not how a low-level library should be designed.

Since this library is about POSIX stuff, you should simply allow **all** POSIX flags, see http://www.unix.com/man-page/posix/3p/open/

> O_NOFOLLOW    If path names a symbolic link, fail and set errno to [ELOOP].

**Comment by joeyh** [comment]
This bug appears to have been fixed, and ought to be closed.

**Comment by RyanGlScott** [comment]
Indeed, this was resolved in c7d88b3612fdf74a7964a670d6e79128f97f46b0.

**Comment by joeyh** [comment]
Ryan Scott wrote:
> Indeed, this was resolved in c7d88b3.

Sorry if I'm being dense, but how does that let a directory stream be
opened with O_NOFOLLOW? openDirStream still takes only a FilePath ..

-- 
see shy jo

**Comment by RyanGlScott** [comment]
Perhaps I misunderstood the scope of this ticket. The issue (as far as I understood it) was the inability specify the `O_NOFOLLOW` flag via the API, and that commit does add a `nofollow` field to `OpenFileFlags`. Is there a remaining issue that should warrant re-opening this ticket?

**Comment by hasufell** [comment]
> Sorry if I'm being dense, but how does that let a directory stream be opened with O_NOFOLLOW? openDirStream still takes only a FilePath ..

`openDirStream` uses `opendir`, which is not a sycall, but a C library function. It doesn't allow to set flags.

Instead you would use `open` to get a file descriptor, followed by `fdopendir` to get the DIR stream. I don't know if we have a function for `fdopendir`, you might have to write it yourself.

**Comment by joeyh** [comment]
Apologies for the noise, I confused this with my other issue for openDirStream O_NOFOLLOW support.
