### ISSUE TITLE
Where are the other open flags

### ISSUE THREAD

**Issue by nh2** [haskell/unix#6]
I'd like to create an FD with `O_CLOEXEC`.

What would be the most high-level way to do that?

http://hackage.haskell.org/package/unix-2.7.0.1/docs/System-Posix-IO.html#v:OpenFileFlags only gives me `append`, `exclusive`, `noctty`, `nonBlock`, `trunc`. What's the idea behind this selection, and can the other flags easily be added?

**Comment by hasufell** [comment]
> @gregorycollins If I want to add some things to this, how would I deal with cross-platform compatibility and what platforms to I have to take care of?
> 
> Relatedly, this is the intersection of supported `O_*` flags for [Linux](http://man7.org/linux/man-pages/man2/open.2.html) and [BSD](http://www.freebsd.org/cgi/man.cgi?query=open&sektion=2):
> 
> ```
> O_APPEND
> O_CLOEXEC
> O_CREAT
> O_DIRECT
> O_DIRECTORY
> O_EXCL
> O_NOCTTY
> O_NOFOLLOW
> O_NONBLOCK
> O_SYNC
> O_TRUNC
> ```
> 
> And of those, the following are not implemented in the `unix` package:
> 
> ```
> O_CLOEXEC
> O_CREAT
> O_DIRECT
> O_DIRECTORY
> O_NOFOLLOW
> O_SYNC
> ```

unix-2.8.0.0 will have:

```hs
data OpenFileFlags =
 OpenFileFlags {
    append    :: Bool,           -- ^ O_APPEND
    exclusive :: Bool,           -- ^ O_EXCL, result is undefined if O_CREAT is False
                                 --
                                 -- __NOTE__: Result is undefined if 'creat' is 'Nothing'.
    noctty    :: Bool,           -- ^ O_NOCTTY
    nonBlock  :: Bool,           -- ^ O_NONBLOCK
    trunc     :: Bool,           -- ^ O_TRUNC
    nofollow  :: Bool,           -- ^ O_NOFOLLOW
                                 --
                                 -- @since 2.8.0.0
    creat     :: Maybe FileMode, -- ^ O_CREAT
                                 --
                                 -- @since 2.8.0.0
    cloexec   :: Bool,           -- ^ O_CLOEXEC
                                 --
                                 -- @since 2.8.0.0
    directory :: Bool,           -- ^ O_DIRECTORY
                                 --
                                 -- @since 2.8.0.0
    sync      :: Bool            -- ^ O_SYNC
                                 --
                                 -- @since 2.8.0.0
 }
```

`O_DIRECT` doesn't seem to be part of POSIX: https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/

So I think this can be closed.

**Comment by nh2** [comment]
@hasufell Thank you, that is very useful.

I am very looking forward to the unix-2.8.0.0 release; with #59 in there we will finally have a chance to tack [The CLOEXEC problem](https://mail.haskell.org/pipermail/haskell-cafe/2015-July/120523.html) across the Haskell ecosystem.

Also thanks for your other recent `unix` efforts!
