### ISSUE TITLE
Misleading error messages in `rename`

### ISSUE THREAD

**Issue by luispedro** [haskell/unix#60]
The `rename` function always mentions the first argument even if the issue is with the second one. For example:

```
rename "file.txt" "directory-which-does-not-exist/file.txt"
```

if `file.txt` exists, but `directory-which-does-not-exist` does not, the error message will say:

```
file.txt: rename: does not exist (No such file or directory)
```

**Comment by oherrala** [comment]
Same issue also in functions ```createLink``` and ```createSymbolicLink```.

POSIX ```rename```'s ```ENOENT``` error doesn't specify which one (target or destination file/path) was the problem.

One way to eliminate the confusion is to call ```throwErrnoIfMinus1_``` in affected functions instead of ```throwErrnoPathIfMinus1_``` to leave out the file/path from produced error message.

**Comment by glguy** [comment]
We could also unconditionally include both paths in the error message as seen below:

```
$ mv bad worse
mv: rename bad to worse: No such file or directory
```

**Comment by harendra-kumar** [comment]
I just spent almost half an hour debugging a problem where I accidentally had a trailing `/` on the linkpath being created via `createSymbolicLink`.
