### ISSUE TITLE
Posix.io.bytestring module uses string instead of bytestring

### ISSUE THREAD

**Issue by cartazio** [haskell/unix#63]
At least for the versions on hackage :(

**Comment by glguy** [comment]
This is by design, all that this module does it make it possible to open an FD with a `RawFilePath` which is a bytestring because POSIX doesn't specify any particular encoding for filenames.

Are you proposing to change the purpose of this module?

**Comment by cartazio** [comment]
More like I was digging into how I'd do posix pipes manipulation and was
suprised. Granted I think bytestring has the ops I need.  Just wanted to
ask in a documented way the answer could be reused next time.

That makes sense.  Thanks !

**Comment by bgamari** [comment]
Eric Mertens <notifications@github.com> writes:

> This is by design, all that this module does it make it possible to open an FD with a `RawFilePath` which is a bytestring because POSIX doesn't specify any particular encoding for filenames.
>
It perhaps wouldn't be a terrible idea to add a note in the Haddocks
mentioning this.

**Comment by cartazio** [comment]
Agreed.  That's probably a good idea.  Better than staying maintainer
folklore.  Does the same rule of thin apply to the other .Bytestring
modules?

**Comment by hvr** [comment]
@cartazio see top of http://hackage.haskell.org/package/unix-2.7.2.0/docs/System-Posix-ByteString.html

> POSIX.1-2008 support with ByteString file paths and environment strings.
>
> This module exports exactly the same API as System.Posix, except that all file paths and environment strings are represented by ByteString instead of String. The System.Posix API implicitly translates all file paths and environment strings using the locale encoding, whereas this version of the API does no encoding or decoding and works directly in terms of raw bytes.

**Comment by mokus0** [comment]
I came across this just now and found it baffling too.  I was expecting fdRead, fdWrite, et al, to operate on `ByteString`s.  I _could_ convert my `Fd`s to `Handle`s but in some applications I specifically want to ultimately use POSIX calls rather than whatever `System.IO` decides to use (presumably C stdio for portability?)

**Comment by hasufell** [comment]
My opinion is that ByteString variants shouldn't mess with `CString` at all (that means convert to `ByteString`, `ShortByteString` or something else that's a no-op).

Whether that's a filepath or not doesn't really matter, does it? Most `CString`s don't have any pre-defined encoding.

**Comment by Bodigrim** [comment]
Essentially anything working through `peekCString*` / `pokeCString*` should not be present under `System.Posix.ByteString` tree, because it involves locale-dependent encoding/decoding, but raison d'etre of `System.Posix.ByteString` is to be locale-independent.

**Comment by hasufell** [comment]
One of the bigger problems seems to be [`GroupEntry`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-User.html#t:GroupEntry) and [`UserEntry`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-User.html#t:UserEntry).

What to do here? Parametrize the type? Add a new type? I think the `String` type here can in fact lead to security vulnerabilities.

**Comment by Bodigrim** [comment]
What POSIX says about username / groupname? Is it just a bytestring with no encoding associated? Or is it supposed to be ASCII subset only?

**Comment by hasufell** [comment]
* https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/pwd.h.html
* https://pubs.opengroup.org/onlinepubs/9699919799/functions/getpwuid.html

I can't see any mention of encoding. It seems it's only implicit that these are NUL terminated. No other guarantees.

**Comment by hasufell** [comment]
I think most of these instances are fixed. Some boring ones involving error types are still there, but not very interesting. I'll open a new ticket for GroupEntry/UserEntry.
