### ISSUE TITLE
accessTimeHiRes / modificationTimeHiRes / statusChangeTimeHiRes do not return subsecond precision on OS X

### ISSUE THREAD

**Issue by jessekempf** [haskell/unix#66]
Hi,

I'm using unix 2.7.2.0 on OS X 10.11.5, Stack is version 1.0.4.3 x86_64, and ghc version 7.10.3. I'm finding that despite the autogenerated `include/HsUnixConfig.h` including
```
#define HAVE_STRUCT_STAT_ST_ATIMESPEC 1
#define HAVE_STRUCT_STAT_ST_CTIMESPEC 1
#define HAVE_STRUCT_STAT_ST_MTIMESPEC 1
```
I'm getting results like:
```
> statusChangeTimeHiRes <$> getFileStatus "/tmp" 
1466637634s
```

When I manually run hsc2hs on a checkout of master, the produced code looks like:
```
accessTimeHiRes (FileStatus stat) =
  unsafePerformIO $ withForeignPtr stat $ \stat_ptr -> do
    sec  <- ((\hsc_ptr -> peekByteOff hsc_ptr 32)) stat_ptr :: IO EpochTime
{-# LINE 292 "System/Posix/Files/Common.hsc" #-}

{-# LINE 296 "System/Posix/Files/Common.hsc" #-}
    nsec <- ((\hsc_ptr -> peekByteOff hsc_ptr 40)) stat_ptr :: IO (Int64)
{-# LINE 297 "System/Posix/Files/Common.hsc" #-}
    let frac = toInteger nsec % 10^(9::Int)

{-# LINE 310 "System/Posix/Files/Common.hsc" #-}
    return $ fromRational $ toRational sec + frat
```

I'm now stuck trying to figure out what to look at next in tracking this problem down. Can you help?

**Comment by glguy** [comment]
Are you storing your files in an HFS+ partition (the default)? HFS+ features a 1-second timestamp resolution!

**Comment by jessekempf** [comment]
@glguy: Well. Yes, as a matter of fact, I am. That would explain it -- for some reason I derped out and didn't write a test in C to figure out what was coming back from `stat(2)`.

Do you think I should add a note about the FS-dependency of timestamp resolution, or is it obvious?

**Comment by ndmitchell** [comment]
The Mac thing surprised me in the past (its amazing an OS still running doesn't have better timestamps), so I think it's worth adding a note.

**Comment by jessekempf** [comment]
Here's the PR: https://github.com/haskell/unix/pull/67. I've copied and pasted the same disclaimer in several places -- is there a way I can DRY this out with Haddock? https://www.haskell.org/haddock/doc/html/ch03s05.html seemed like it would fit the bill, but it's not clear how I would go about using this named block of documentation.

**Comment by glguy** [comment]
This isn't a bug in the library, and discussion about the documentation improvement can happen on the PR improving the documentation, so I'm closing this ticket.
