### ISSUE TITLE
`readdir_r` is deprecated

### ISSUE THREAD

**Issue by erikd** [haskell/unix#70]
Building revision 40820da5fb on Debian Testing I get:
```
cbits/HsUnix.c: In function ‘__hscore_readdir’:

cbits/HsUnix.c:64:3: error:
     warning: ‘readdir_r’ is deprecated [-Wdeprecated-declarations]
       res = readdir_r(dirPtr, p, pDirEnt);
       ^~~

In file included from include/HsUnix.h:71:0: error:
    0,
                     from cbits/HsUnix.c:9:

```
 According to the man page:

> This function is deprecated; use readdir(3) instead.
>
> The readdir_r() function was invented as a reentrant version of readdir(3). It reads the next directory entry from the directory stream dirp, and returns it in the caller-allocated buffer pointed to by entry.
>
> It is expected that a future version of POSIX.1 will make readdir_r() obsolete, and require that readdir() be thread-safe when concurrently employed on different directory streams.

Since the implementation already has `#if HAVE_READDIR_R` the fix mostly involves detecting whether `readdir_r` is deprecated or not and setting `HAVE_READDIR_R` appropriately.

**Comment by erikd** [comment]
The opinion some placed is to just drop `readdir_r` all together : https://www.spinics.net/lists/fedora-devel/msg222990.html

**Comment by hvr** [comment]
@erikd fair enough... but is it safe to use `readdir(3)` instead of `readdir_r(3)` on say older Linux LTS distros (or other conservative Unices with very long lifecycles)?

**Comment by erikd** [comment]
@hvr really not sure. The Fedora people are using some ugly CPP to check for Glibc verions:
```
#if !defined(__GLIBC__) || (__GLIBC__ < 2) || ((__GLIBC__ == 2) && (__GLIBC_MINOR__ < 23))

    /* readdir_r is deprecated with newer GLIBC */
    struct dirent entry, *iter = 0;
    while ( (errno = readdir_r( d.d, &entry, &iter )) == 0 && iter ) {
        std::string ename( entry.d_name );
#else
   /* use readdir */
```
Do we want to do something similar?

**Comment by hvr** [comment]
Well, it's just a deprecation warning after all, is it? Do we really have to silence it? If `readdir_r(3)` gets finally removed, our autoconf tests would do the right thing anyway...

**Comment by erikd** [comment]
We need to silence it because without it being silenced, its not possible to build GHC with `-Werror`.

**Comment by ip1981** [comment]
I know it is a bit late, but adding a check in `configure.ac` would do the best job. I. e. check for `readdir_r` first, if not found - use `readdir` :)
