### ISSUE TITLE
time-1.7 is released

### ISSUE THREAD

**Issue by debug-ito** [haskell/unix#80]
time-1.7 is released. Would you check if it builds OK, and update .cabal file?

**Comment by hvr** [comment]
Sure, but you're downplaying the work needed ;-) I wouldn't be a responsible maintainer if I merely relied on compilation to decide that it's ok to relax the upper bound...

**Comment by hvr** [comment]
Also meta-data edited for the already released 2.7.2.1: http://hackage.haskell.org/package/unix-2.7.2.1/revisions/

**Comment by debug-ito** [comment]
Thanks!
