### ISSUE TITLE
Use of empty FilePath to indicate end of DirStream seems deeply questionable

### ISSUE THREAD

**Issue by ezyang** [haskell/unix#81]
For example:

```
readDirStream :: DirStream -> IO RawFilePath
readDirStream (DirStream dirp) =
  alloca $ \ptr_dEnt  -> loop ptr_dEnt
 where
  loop ptr_dEnt = do
    resetErrno
    r <- c_readdir dirp ptr_dEnt
    if (r == 0)
         then do dEnt <- peek ptr_dEnt
                 if (dEnt == nullPtr)
                    then return BC.empty
                    else do
                     entry <- (d_name dEnt >>= peekFilePath)
                     c_freeDirEnt dEnt
                     return entry
         else do errno <- getErrno
                 if (errno == eINTR) then loop ptr_dEnt else do
                 let (Errno eo) = errno
                 if (eo == 0)
                    then return BC.empty
                    else throwErrno "readDirStream"
```

Wouldn't it be far better if we returned 'Maybe RawFilePath'? Ditto for FilePath API.

**Comment by glguy** [comment]
I'm inclined to agree. It doesn't seem to be the case that empty bytestrings are used anywhere else in the `unix` package in this fashion. Even worse, this behavior doesn't appear to be documented. 

https://github.com/haskell/unix/blob/7b20b4cbc35a2fea3f26c988f9b2a95640babaaa/System/Posix/Directory/ByteString.hsc#L88

**Comment by glguy** [comment]
We'll want to fix the FilePath version, too.

https://github.com/haskell/unix/blob/7b20b4cbc35a2fea3f26c988f9b2a95640babaaa/System/Posix/Directory.hsc#L91

**Comment by hvr** [comment]
Btw, do we know when this behavior was introduced?

**Comment by hvr** [comment]
The 2.8 milestone is only tentative; we probably want to do this backward compat anyway by introducing new functions and deprecating the old ones

**Comment by spl** [comment]
@ezyang Absolutely! I'm using this package for the first time and encountering this issue. It's like a return to the untyped C world.
