### ISSUE TITLE
Does not typecheck with time-1.8 (HEAD)

### ISSUE THREAD

**Issue by ezyang** [haskell/unix#82]
```
libraries/unix/System/Posix/Files/Common.hsc:356:14: error:
    • No instance for (Fractional POSIXTime)
        arising from a use of ‘fromRational’
    • In the second argument of ‘($)’, namely
        ‘fromRational $ toRational sec + frac’
      In a stmt of a 'do' block:
        return $ fromRational $ toRational sec + frac
      In the expression:
        do sec <- ((\ hsc_ptr -> peekByteOff hsc_ptr 104)) stat_ptr ::
                    IO EpochTime
           nsec <- ((\ hsc_ptr -> peekByteOff hsc_ptr 112)) stat_ptr ::
                     IO (Int64)
           let frac = toInteger nsec % 10 ^ (9 :: Int)
           return $ fromRational $ toRational sec + frac

libraries/unix/System/Posix/Files/Common.hsc:419:38: error:
    • No instance for (Real POSIXTime)
        arising from a use of ‘toRational’
    • In the second argument of ‘($)’, namely ‘toRational t’
      In the expression: properFraction $ toRational t
      In a pattern binding: (sec', frac') = properFraction $ toRational t

libraries/unix/System/Posix/Files/Common.hsc:449:38: error:
    • No instance for (Real POSIXTime)
        arising from a use of ‘toRational’
    • In the second argument of ‘($)’, namely ‘toRational t’
      In the expression: properFraction $ toRational t
      In a pattern binding: (sec', frac') = properFraction $ toRational t
```

**Comment by RyanGlScott** [comment]
There's a `time-1.9`? I thoughf that HEAD was only at version `1.8`?

**Comment by hvr** [comment]
I'm quite positive @ezyang meant time-1.8

**Comment by winterland1989** [comment]
Yes, the new `POSIXTime` is intended to be a low level type to make the conversion between POSIX presentation and high level types more efficient AFAICT,  i 'm not having any particular feelings about the `Fractional` instance, if there is too much breakage I guess it should be add then.

**Comment by RyanGlScott** [comment]
Since `POSIXTime` was previously just a type synonym for `NominalDiffTime` (a.k.a. `Pico`, a.k.a `Fixed E12`), if we want to avoid other breakages like this, we should mirror all instances for `Fixed a` as well. From a quick glance at [`Fixed`'s Haddocks](https://www.stackage.org/haddock/lts-7.13/base-4.9.0.0/Data-Fixed.html#t:Fixed), it looks like that would include:

* `Data`
* `Enum`
* `Fractional`
* `Num`
* `Read`
* `Real`
* `RealFrac`
* `Show`

**Comment by ezyang** [comment]
Sorry, I mean 1.8! Edited.

**Comment by AshleyYakeley** [comment]
HEAD is not in a stable state right now. I am considering reverting the changes to `POSIXTime` and adding a `RawTime` instead, to maintain compatibility.

**Comment by hvr** [comment]
@winterland1989 @AshleyYakeley ok, but while adding a new `RawTime` provides maximum compatibility, this also means that `unix` won't be able to benefit from this, unless we start duplicating the API (similiar to what we already do for RawFilePath <-> FilePath; for RawTime we'd probably get away duplicating just one/two module or so)

(...or we leverage @ezyang's backpack for abstracting over POSIXTime/RawTime)

**Comment by winterland1989** [comment]
I'm inclined to change `POSIXTime` directly for the same reason. My patch start with `POSIXTimeRaw` routine, then i removed it and changed `POSIXTime` directly in next commits followed discussion with @AshleyYakeley. 

The situation now is quite frustrating, while we're still looking for a judgement on `POSIXTime` changing itself, here's what i see as an appropriate solution if we do change it:

+ Add missing `Num, Real, RealFrac, Fractional` instance.
+ Derive `Show, Read, Data` instances.
+ Document the change of `POSIXTime` and its instances.
+ Document the removal of `Enum` instance.

**Comment by AshleyYakeley** [comment]
I'm trying to avoid breaking downstream packages by changing `POSIXTime`. I figure if we introduce a new type, it should have a new name.

**Comment by AshleyYakeley** [comment]
I believe this issue can be closed.

**Comment by RyanGlScott** [comment]
Given that `time-1.8` has been released (without this breaking change) and `unix` compiles just fine with it, I'll close this issue.
