### ISSUE TITLE
Export FileStatus constructor

### ISSUE THREAD

**Issue by nh2** [haskell/unix#87]
The `FileStatus` constructor is not exported which makes it impossible for me to write a faster `getFileStatus` implementation (see e.g. https://ghc.haskell.org/trac/ghc/ticket/13296) without `unsafeCoerce`.

Please export the `FileStatus` constructor and similar constructors!

**Comment by hs-viktor** [comment]
Would you like to propose a PR?

**Comment by nh2** [comment]
PR in #204
