### ISSUE TITLE
closeFd doesn't check for EINTR

### ISSUE THREAD

**Issue by nh2** [haskell/unix#88]
From `man 2 open`:

`EINTR  While blocked waiting to complete an open of a slow device (e.g., a FIFO; see fifo(7)), the call was interrupted by a signal handler; see signal(7).`

From `man 2 close`:

`EINTR  The close() call was interrupted by a signal; see signal(7).`

The situation in `unix`:

* For `open` [the code doesn't handle `EINTR`](https://github.com/haskell/unix/blob/7b20b4cbc35a2fea3f26c988f9b2a95640babaaa/System/Posix/IO/Common.hsc#L166)
* For `close` [the code doesn't handle `EINTR`](https://github.com/haskell/unix/blob/7b20b4cbc35a2fea3f26c988f9b2a95640babaaa/System/Posix/IO/Common.hsc#L194)

**Comment by nh2** [comment]
I must correct myself, `open` does handle it, but not in `open_` but in `openFd` [here](https://github.com/haskell/unix/blob/38d445e5830fb53efd7133f688b37d85e639d23e/System/Posix/IO/ByteString.hsc#L84).

`close` still has the problem.

**Comment by glguy** [comment]
It's not obvious that it would be OK to handle EINTR on close. As a starting point consider https://lwn.net/Articles/576478/

I don't know the correct answer. I just remembered that there was an issue around this topic, and I'm  adding this link to the discussion early.

**Comment by nh2** [comment]
That's a good link indeed. The key concern in there seems to be that after `EINTR` the FD might be closed, so that another call to close would not be sensible (and I assume likely return `EBADF`).

We might be able to handle this by checking if the 2nd or following calls to `close()` return `errno = EBADF`; these stackoverflow answers seem to use that for checking too:

* http://stackoverflow.com/a/12340725
* http://stackoverflow.com/a/19660456

**Comment by glguy** [comment]
File descriptor allocation encourages reuse. Calling close again and checking for EBADF could easily be closing a new, valid file descriptor.

**Comment by zenhack** [comment]
Calling close a second time unconditionally is invalid, for the discussed reasons.

On Linux, there is no cleanup to do after close returns EINTR, or for that matter any other error. The first thing the syscall does is remove the fd from the process's fd table, so in no circumstances will the fd be valid upon return. Other implementations may differ; the portability story on this point is not good.

**Comment by nh2** [comment]
@zenhack Do you have a reference for that? It would be nice to link it from a comment.

**Comment by zenhack** [comment]
3rd paragraph in the "dealing with errors" section:

http://man7.org/linux/man-pages/man2/close.2.html#NOTES

A bit further down there's discussion of EINTR specifically, and while
it is always closed on Linux, POSIX leaves its state unspecified.

**Comment by zenhack** [comment]
...and here's the POSIX:

http://pubs.opengroup.org/onlinepubs/9699919799/functions/close.html
