### ISSUE TITLE
cfmakeraw

### ISSUE THREAD

**Issue by joeyh** [haskell/unix#93]
Would be helpful to have cfmakeraw(3) exported from System.Posix.Terminal.

It is needed when eg, writing a haskell program that works similarly to `script`. 

I emulated cfmakeraw in my code like this:

                        as `withoutMode` IgnoreBreak
                            `withoutMode` InterruptOnBreak
                            `withoutMode` CheckParity
                            `withoutMode` StripHighBit
                            `withoutMode` MapLFtoCR
                            `withoutMode` IgnoreCR
                            `withoutMode` MapCRtoLF
                            `withoutMode` StartStopOutput
                            `withoutMode` ProcessOutput
                            `withoutMode` EnableEcho
                            `withoutMode` EchoLF
                            `withoutMode` ProcessInput
                            `withoutMode` KeyboardInterrupts
                            `withoutMode` ExtendedFunctions
                            `withoutMode` EnableParity

That was tedious to come up with, and it doesn't include the CSIZE setting that cfmakeraw does. And it may be that some unix has a cfmakeraw that differs in some subtle way, perhaps unsetting an OS-specific extension, in which case my haskell emulation would be buggy.

**Comment by hvr** [comment]
Unfortunately, `cfmakeraw(3)` doesn't seem to be part of any POSIX spec?

**Comment by joeyh** [comment]
Herbert Valerio Riedel wrote:
> Unfortunately, cfmakeraw(3) doesn't seem to be part of any POSIX spec?

Right, on linux the man page says it's nonstandard, notes that "the
BSDs" also implement it.

-- 
see shy jo

**Comment by hvr** [comment]
Well, the stated scope/purpose of the `unix` package (which should have really be called `posix` instead) is

> This package gives you access to the set of operating system services standardised by POSIX.1-2008 (or the IEEE Portable Operating System Interface for Computing Environments - IEEE Std. 1003.1).

So I'm rather reluctant to add support for APIs not standardised by POSIX. :-/

**Comment by joeyh** [comment]
Could the TerminalAttributes internals be exposed? Then it would be
possible for a third party to eg use FFI to run cfmakeraw() on it.

-- 
see shy jo

**Comment by hs-viktor** [comment]
Inclined to close.  Is this still relevant?
