### ISSUE TITLE
getDirectoryContents:readDirStream: invalid argument (Invalid argument)

### ISSUE THREAD

**Issue by domenkozar** [haskell/unix#96]
I've spotted a transient error on macOS travis-ci job:

```
Jun 05 09:20:40 .stack-work/dist/x86_64-osx-nix/Cabal-1.24.2.0/build/.stack-work/dist/x86_64-osx-nix/Cabal-1.24.2.0/build/autogen:
Jun 05 09:20:40 getDirectoryContents:readDirStream: invalid argument (Invalid argument)
Jun 05 09:20:46 Completed 107 action(s).
```

Workaround is to restart the CI job, but I wonder what goes wrong?

Source: https://github.com/haskell/unix/blob/7b20b4cbc35a2fea3f26c988f9b2a95640babaaa/System/Posix/Directory.hsc#L91

**Comment by domenkozar** [comment]
Invoked from Cabal:

```
$ git grep "getDirectoryContents "
Cabal/Distribution/PackageDescription/Check.hs:      getDirectoryContents = System.Directory.getDirectoryContents . relative,
Cabal/Distribution/PackageDescription/Check.hs:    getDirectoryContents :: FilePath -> m [FilePath],
Cabal/Distribution/PackageDescription/Check.hs:      files <- getDirectoryContents ops dir
Cabal/Distribution/Simple/GHC/Internal.hs:        objss <- mapM getDirectoryContents dirs
Cabal/Distribution/Simple/LHC.hs:        objss <- mapM getDirectoryContents dirs
Cabal/Distribution/Simple/Test.hs:    getDirectoryContents testLogDir
Cabal/Distribution/Simple/UHC.hs:          mapM (\ d -> getDirectoryContents d >>= filterM (isPkgDir (display compilerid) d))
Cabal/Distribution/Simple/Utils.hs:      (files, dirs') <- collect [] [] =<< getDirectoryContents (topdir </> dir)
Cabal/Distribution/Simple/Utils.hs:    files <- getDirectoryContents (dir </> dir')
Cabal/Distribution/Simple/Utils.hs: = do files <- getDirectoryContents dir
Cabal/Distribution/Simple/Utils.hs:    files <- getDirectoryContents dir
```

**Comment by nh2** [comment]
From the [man page](http://man7.org/linux/man-pages/man2/readdir.2.html) on the `readdir` syscall on Linux;

`EINVAL Result buffer is too small.`

But this is on OSX, not sure if it's the same there.

I'm not sure how to look up when `readdir()` should return `EINVAL` on OSX. [Their man page doesn't list any error codes.](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/readdir.3.html). According to https://apple.stackexchange.com/questions/239484/does-apple-provide-a-web-site-with-content-of-man-pages-for-the-command-line-c

> Many of the Apple man pages do not keep up with the actual program options

Can we obtain the source code of the current version of `readdir()` in OSX?

---

Also, I found [this golang commit from 2 years ago](https://codereview.appspot.com/119530044/) that says:

```
On OS X 10.10 Yosemite, if you have a directory that can be returned
in a single getdirentries64 call (for example, a directory with one file),
and you read from the directory at EOF twice, you get EOF both times:
        fd = open("dir")
        getdirentries64(fd) returns data
        getdirentries64(fd) returns 0 (EOF)
        getdirentries64(fd) returns 0 (EOF)

But if you remove the file in the middle between the two calls, the
second call returns an error instead.
        fd = open("dir")
        getdirentries64(fd) returns data
        getdirentries64(fd) returns 0 (EOF)
        remove("dir/file")
        getdirentries64(fd) returns ENOENT/EINVAL

Whether you get ENOENT or EINVAL depends on exactly what was
in the directory. It is deterministic, just data-dependent.

This only happens in small directories. A directory containing more data
than fits in a 4k getdirentries64 call will return EOF correctly.
(It's not clear if the criteria is that the directory be split across multiple
getdirentries64 calls or that it be split across multiple file system blocks.)
```

So it sounds like it's an OSX bug introduced in 10.10.

Further

> C program reproducing the issue, also at http://swtch.com/~rsc/readdirbug.c:

@domenkozar Could you try this C program they mention?

At the end they write

> I filed Apple Bug 17978656.

But apparently Apple bugs aren't public? Very useful :/

**Comment by domenkozar** [comment]
The bug happens on macOS 10.12 (xcode 8.3) so it's still present.

**Comment by hs-viktor** [comment]
Is this still an issue with current MacOS versions (Monterey or other recent)?

**Comment by andreasabel** [comment]
> Is this still an issue with current MacOS versions (Monterey or other recent)?

Is there a reproducer?  (Otherwise I cannot test it.)

The C reproducer quoted above does not indicate a problem on Mac OS Mojave (10.14):
```
$ gcc readdirbug.c 
abel:13:52:37::~/play/c/bugs$ ./a.out 
mkdir /tmp/readdirbug
create /tmp/readdirbug/file1

opendir /tmp/readdirbug
readdir: found .
readdir: found ..
readdir: found file1
readdir: EOF
readdir: EOF
readdir: EOF
closedir

opendir /tmp/readdirbug
readdir: found .
readdir: found ..
readdir: found file1
readdir: EOF
rm /tmp/readdirbug/file1
readdir: EOF
readdir: EOF
closedir
ok - everything worked
```

I'd close this issue...

**Comment by hs-viktor** [comment]
This appears to be no longer applicable.
